server:
  port: 8007

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ltbanking
    username: userapp
    password: 1serBkg24
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, threaddump, mappings, prometheus
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
      show-components: always
      enabled: true