server:
  port: 8001

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, threaddump, mappings, prometheus
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
      show-components: always
      enabled: true