server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: http://localhost:8005/
          predicates:
          - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, beans, threaddump, mappings, gateway
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
      show-components: always
      enabled: true
    gateway:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans