services:
  db-mysql:
    container_name: db-mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ltbanking
      MYSQL_USER: userapp
      MYSQL_PASSWORD: 1serBkg24
      MYSQL_ROOT_PASSWORD: 4kDGQDYe4JxDjRd
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ./logs:/var/log
    command: -config.file=/etc/promtail/config.yml

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    ports:
      - "9411:9411"

  config-service:
    build:
      context: config-service
      dockerfile: Dockerfile
    container_name: config-service
    ports:
      - "8002:8002"
    healthcheck:
      test: curl --fail http://localhost:8002/user-service/default  || exit 1
      interval: 5s
      timeout: 2s
      retries: 10


  discovery-service:
    build:
      context: discovery-service
      dockerfile: Dockerfile
    container_name: discovery-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - "8001:8001"
    healthcheck:
      test: curl --fail http://localhost:8001/eureka/v2/apps || exit 1
      interval: 5s
      timeout: 2s
      retries: 10

  user-service:
    build:
      context: user-service
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      discovery-service:
        condition: service_healthy
    volumes:
      - ./logs:/logs
    ports:
      - "8005:8005"

  account-service:
    build:
      context: account-service
      dockerfile: Dockerfile
    container_name: account-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      discovery-service:
        condition: service_healthy
    ports:
      - "8006:8006"

  card-service:
    build:
      context: card-service
      dockerfile: Dockerfile
    container_name: card-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      discovery-service:
        condition: service_healthy
    ports:
      - "8007:8007"


  gateway-service:
    build:
      context: gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      discovery-service:
        condition: service_healthy
    ports:
      - "8000:8000"


volumes:
  mysql-volume:
    driver: local