services:
  db_mysql:
    container_name: db_mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ltbanking
      MYSQL_USER: userapp
      MYSQL_PASSWORD: 1serBkg24
      MYSQL_ROOT_PASSWORD: 4kDGQDYe4JxDjRd
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    ports:
      - "9411:9411"

