services:
  db_mysql:
    container_name: db_mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ltbanking
      MYSQL_USER: userapp
      MYSQL_PASSWORD: 1serBkg24
      MYSQL_ROOT_PASSWORD: 4kDGQDYe4JxDjRd
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - banking-nt

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - banking-nt

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - banking-nt

networks:
  banking-nt:
    driver: bridge

volumes:
  mysql-volume:
    driver: local