scrape_configs:
  - job_name: 'banking-lt-microservice-metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8005']
        labels:
          application: 'user-service'
      - targets: [ 'host.docker.internal:8006' ]
        labels:
          application: 'account-service'
      - targets: [ 'host.docker.internal:8007' ]
        labels:
          application: 'card-service'