spring:
  application:
    name: account-service
  config:
    import: "optional:configserver:http://config-service:8002"
  activate:
    on-profile: docker
---
spring:
  application:
    name: account-service
  config:
    import: "optional:configserver:http://localhost:8002"